### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @spicelang.

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
I manage winget-pkgs-automation, but since it is getting difficult for me to maintain 1000+ packages, I'm requesting devs to migrate to my action since it's easier to maintain. Hence, I ask you to please switch to action, because I cannot guarantee that every package will be updated by automation.

**Comment by marcauberer** [comment]
Your action does not work with our release workflow. We do not create GitHub releases manually, they are created automatically by another workflow. That means that GitHub will not trigger your workflow.

Feature request: Allow events other than the release event when the action gets the release name as an argument.

**Comment by vedantmgoyal2009** [comment]
Thanks for the idea. Please re-open the PR so that when I can update it to work with your existing workflow and then you can merge :)

**Comment by marcauberer** [comment]
@vedantmgoyal2009 any progress on this? If not, I am going to close the pr for now.

**Comment by vedantmgoyal2009** [comment]
The work is in progress. You can see the [latest commit](https://github.com/vedantmgoyal2009/winget-releaser/commits/main), but some finishing touches are yet to be applied. You can probably expect it by this weekend.

**Comment by vedantmgoyal2009** [comment]
@marcauberer I've merged the winget-release step into the existing workflow. Please review and merge. Also, don't forget to:

> 1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
> 2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @spicelang.

**Comment by vedantmgoyal2009** [comment]
@marcauberer the 3 PRs are awaiting your kind attention:
- https://github.com/spicelang/spice/pull/165
- https://github.com/compose-generator/compose-generator/pull/349
- https://github.com/compose-generator/ccom/pull/157

**Comment by marcauberer** [comment]
@vedantmgoyal2009 could you revert the changes to the matrix config in all three prs? It seems not to be semantically equivalent.

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 could you revert the changes to the matrix config in all three prs? It seems not to be semantically equivalent.

Done.

**Review by marcauberer — APPROVED** [review]

**Pull request merged**
